# Generated by Django 3.0.1 on 2020-06-21 20:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='comm',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('music', 'Music'), ('photography', 'Photography'), ('acting', 'Acting'), ('art', 'Acting'), ('travel', 'Travel'), ('sports', 'Sports'), ('humanity', 'Humanity'), ('dance', 'Dance')], max_length=255),
        ),
    ]
